apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.service.name.redis }}
spec:
  selector:
    app: {{ $.Values.deployment.name.redis }}
  ports:
  - name: {{ $.Values.service.portname.redis }}
    port: {{ $.Values.service.port.redis }}
    targetPort: {{ $.Values.service.targetport.redis }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.service.name.web }}
spec:
  type: NodePort
  selector:
    app: {{ $.Values.deployment.name.web }}
  ports:
  - name: {{ $.Values.service.portname.web }}
    port: {{ $.Values.service.port.web }}
    targetPort: {{ $.Values.service.targetport.web }}
    nodePort: 30007