name: test-workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Repository branch or tag'
        required: true
  push:
    tags:
      - '*'
  
jobs:

  build:
    runs-on: ubuntu-latest
    environment: helm

    steps:
      - name: Set Tag on Push
        if: github.event_name == 'push'
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: docker login
        run: docker login -u chanut995953 -p ${{ secrets.DOCKER_REGISTRY }}

      - name: build and push
        run: |
          docker build -t chanut995953/lab:${{ env.IMAGE_TAG }} docker/
          docker push chanut995953/lab:${{ env.IMAGE_TAG }}

  sync-image:
    needs: build
    runs-on:  ubuntu-latest
    name: sync to acr
    environment:
      name: prd
    steps:
      - name: Set Tag on Push
        if: github.event_name == 'push'
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
      - name: Log in to the github Container registry
        if: github.event_name == 'push'
        run: echo ghcr
      - name: Log in to the Azure Container registry
        if: github.event_name == 'push'
        run: echo acr
      - name: sync image to ACR
        if: github.event_name == 'push'
        run: echo sync
      - name: clean local tags
        if: github.event_name == 'push'
        run: echo clean
           
  deploy-microservice:
    needs: sync-image
    runs-on:  prd
    name: Deploy Microservice
    environment:
      name: prd
    steps:
      - name: Set Tag on Push
        if: github.event_name == 'push'
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
      - name: Login via Azure CLI
        id: az-login
        run: echo login
      - name: Set Kubernetes Context
        id: aks-login
        run: echo setup

      # HELM DEPLOY OR UPGRADE TO AKS
      - name: Helm Deploy and Upgrade to AKS
        run: echo Deploy
