name: Helm-Lab

on:
  workflow_dispatch:
  push:
    branches:
      - lab

jobs:
  any_name:
    runs-on: lab
    steps:
      - name: Test Step
        shell: bash
        run: |
          echo "Test"
