name: Helm-Lab

on:
  workflow_dispatch:
  push:
    branches:
      - helm

jobs:

  build:
    runs-on: lab
    environment: helm
    steps:
      - name: clean
        run: rm -rf click-counter
      - name: Generate tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1
        with:
          registries: |
            docker.io
      - name: git checkout
        run: git clone -b helm https://github.com/cnsj49/click-counter.git

      - name: docker login
        run: |
          echo ${{ secrets.DOCKER_REGISTRY }}
          docker login -u chanut995953 -p ${{ secrets.DOCKER_REGISTRY }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
