name: Lab-Workflow
on:
  push:
    branches:
      - lab
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname
  deploy: 
    runs-on: lab
    steps:
      - name: check github environment
        run: hostname