name: Helm-Lab

on:
  workflow_dispatch:
  push:
    branches:
      - lab

jobs:

  prepare:
    runs-on: lab
    steps:
      - name: Set Tag on Workflow Dispatch
        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

  build:
    runs-on: lab
    needs: prepare
    environment: helm
    steps:
      - name: clean
        run: rm -rf click-counter
      - name: git checkout
        run: git clone -b helm https://github.com/cnsj49/click-counter.git

      - name: docker login
        run: |
          echo ${{ secrets.DOCKER_REGISTRY }}
          docker login -u chanut995953 -p ${{ secrets.DOCKER_REGISTRY }}
        
      - name: build and push
        run: |
          cd click-counter 
          docker build -t chanut995953/click-counter:$GITHUB_ENV .
          docker push chanut995953/click-counter:$GITHUB_ENV
