name: Lab-Workflow
on:
  push:
    branches:
      - lab
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname
      
      - name: create variable 
        run: echo "BUILD_ARGS=dev-1.0.0" >> $GITHUB_ENV

      - name: build application 
        run: echo "build for ${{ env.WORDING }} by $BUILD_ARGS"
        
  deploy: 
    runs-on: lab
    steps:
      - name: check github environment
        run: hostname